import os

POSTGRES_HOST = os.getenv("POSTGRES_HOST")
KAFKA_HOST = os.getenv("KAFKA_HOST")
PUSHPIN_INTERNAL_HOST = os.getenv("PUSHPIN_INTERNAL_HOST")
PUSHPIN_EXTERNAL_HOST = os.getenv("PUSHPIN_EXTERNAL_HOST")
