import os

POSTGRES_HOST = os.getenv("POSTGRES_HOST")
POSTGRES_DB = os.getenv("POSTGRES_DB")
POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
KAFKA_HOST = os.getenv("KAFKA_HOST")
PUSHPIN_INTERNAL_HOST = os.getenv("PUSHPIN_INTERNAL_HOST")
PUSHPIN_EXTERNAL_HOST = os.getenv("PUSHPIN_EXTERNAL_HOST")
